# ----
# Site

title: SerHi
url: 'https://csegura.github.io'
baseurl: '/serhi'
google_analytics_key: G-KNBRLHS09Z 
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: assets/img/img.png
description: Series Historicas de Datos
author: 
  name: carlos segura
  email:
  twitter: romheat # twitter username without the @ symbol
social:
  name: Edition Template
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-feed
  - jekyll-datapage-generator

collections:
  docs:
    title: Documentation
    permalink: /docu/:path/
    output: true
  notebooks:
    title: notebooks
    permalink: /notebooks/:path/
    output: true

page_gen-dirs: true

page_gen:
- data: series
  template: serie
  index_files: false
  name: nombre
  #name_expr: [a Ruby expression to generate the filename (alternative to name)]
  title: nombre
  #title_expr: [a Ruby expression to generate the filename (alternative to title)]
  #extension: md #[extension used to generate the filename]
  #filter: [property to filter data records by]
  #filter_condition: [a Ruby expression to filter data]
  #page_data_prefix: [prefix used to name variables]
  #debug: true #[boolean, if true output more informative messages]
- data: series
  dir: ipynb_src
  template: github_ipynb_src
  name: nombre
  title: nombre
- data: series
  dir: ipynb_pro
  template: github_ipynb_pro
  name: nombre
  title: nombre  

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      category: other
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/