source 'https://rubygems.org'

gem 'jekyll', '3.9.2'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.16.0'
  gem 'jekyll-seo-tag', '2.5.0'
  gem 'jekyll-sitemap', '1.2.0'
  gem 'kramdown-parser-gfm'
  gem 'faraday-retry'
  gem 'jekyll-datapage-generator'
end
