name: Publish Web

on:
  #push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Only trigger, when the runner workflow succeeded
  workflow_run:
    workflows: ["runner"]
    types:
      - completed

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Specify the target branch (optional)
    - uses: helaili/jekyll-action@v2.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1